handlers.go
handlers_test.go

returns 200 instead of 302 when print=yes is in query string

add print mode

---

.gitignore
tests/e2e/README.md
tests/e2e/conftest.py
tests/e2e/requirements.txt
tests/e2e/setup.cfg
tests/e2e/tests/base.py
tests/e2e/tests/test_redirects.py

Consolidate QA's end-to-end tests into the go-bouncer project repository and decommission [bouncer-tests](https://github.com/mozilla/bouncer-tests/).

Move e2e tests into project repository

---

tests/e2e/tests/test_redirects.py

Some recent changes updated the how non-SSL versions are served. Currently this is only on stage.
https://bugzilla.mozilla.org/show_bug.cgi?id=1299163#c1

update SSL rule set the e2e tests use

---

tests/e2e/tests/test_redirects.py

Add some additional alias checks for the winxp tests.
Also segmented out the `beta-latest` check since it's now a moving target.
/cc @stephendonner

winxp: add additional aliases and add beta-latest test

---

tox.ini

Bump `requests` to the latest version. Used by our e2e tests.
r? @stephendonner + @mozilla/web-qa-sorcerers

bump requests to 2.11.0

---

tests/e2e/tests/test_redirects.py

For winxp builds, beta versions are _currently_ pinned to 49.0b10.
Stage db isn't sync'd to prod, so run these tests again download.mozilla.org

pin beta versions to b10

---

setup.cfg

Quiets "13:45:32 WC1 None [pytest] section in setup.cfg files is deprecated, use [tool:pytest] instead."
@m8ttyB r?

Quell pytest warning

---

tests/e2e/tests/test_redirects.py

This is the real deal 👍 
A new set of rules landed for the winxp builds, they're now on the release channel. 
* Changes currently reflect the behavior of production.
* Tests will fail when run against stage until [bug 1304116](https://bugzilla.mozilla.org/show_bug.cgi?id=1304116) is resolved.
* A plan to have prod and stage sync'd in a more timely manner is in the works.
r? @stephendonner

update winxp checks

---

tests/e2e/tests/test_redirects.py

sha1 builds have been unpinned.

update ie6 sha1 beta rules

---

tests/e2e/tests/test_redirects.py

releng introduced an additional rule set that changes the behavior of the`beta` alias, from version `49` onward it moves with the release train.
* I added an explicit assert for the `sha1` alias.
* Added a `raise Exception()` to an `else` statement.
* Refactored comments and moved `latest-beta` to an associated `elif` block.

new sha1 beta ruleset

---

tests/e2e/Jenkinsfile

The `ircNotification` step has been implemented in the [fxtest shared library](https://github.com/mozilla/fxtest-jenkins-pipeline). We have this set up in our Jenkins instances.

Switch to the fxtest shared library

---

tests/e2e/requirements/tests.txt

So this is potentially interesting, my current best guess is that when `requests` was bumped to `2.13` in pr #77 this manifested. I'm also not sure how we missed this during the review process.
`request==2.13.0` changes the behavior of the library by not loading `idna` unless it is determined to be needed ([release notes](https://pypi.python.org/pypi/requests/).
By explicitly installing the security package, `requests[security]==2.13.0`, we force 3 additional packages to be installed, which allow for "better" SSL handling [[0](http://stackoverflow.com/questions/31811949/pip-install-requestssecurity-vs-pip-install-requests-difference)].
* pyOpenSSL
* cryptography
* idna
Successful run:
[http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/bouncer.adhoc/39/](http://webqa-ci-staging1.qa.scl3 …

bug: update to requests[security]

---

tests/e2e/tests/test_redirects.py

As expected, the e2e tests are failing.
With the release of the new `52.0esr.exe` build the tests have been greatly simplified. Regardless of requested build ie 6 should be served 1 build.

update ie tests to reflect new esr builds

---

tests/e2e/Jenkinsfile

Due to Pipeline Model Definition changes
@davehunt @oremj r?

Pass 'xterm' in to ansiColor()

---

tests/e2e/Jenkinsfile
tests/e2e/tests/test_redirects.py
tests/e2e/tests/utils.py

Several things conspired to add confusion, but the tests ultimately did the right thing; caught errors and helped QA have clarifying conversations with releng.
Tests were effected by issues that arose during the initial ESR release, followed by the subsequent dot release. Most recently pr #93 hit an issue where [bug 1350468](https://bugzilla.mozilla.org/show_bug.cgi?id=1350468) was discovered, this has since been fixed.
* update IE6 esr version to recent dot release - `52.0.1esr`
* Update alias tests to use`'FIREFOX_ESR_NEXT': 'firefox-esr-latest'`
* re-enable email notifications

update utils to use the FIREFOX_ESR_NEXT key

---

tests/e2e/tests/test_redirects.py

This pr updates the IE6 tests to point to the `52.0.2esr.exe` build. It also xfails the aliases that are incorrectly redirecting to `52.0.1esr`.
Closes #100 
> tox -- -k ie
py27 installed: apipkg==1.4,appdirs==1.4.3,asn1crypto==0.22.0,beautifulsoup4==4.5.3,blessings==1.6,cffi==1.10.0,cryptography==1.8.1,enum34==1.1.6,execnet==1.4.1,idna==2.5,ipaddress==1.0.18,mozlog==3.4,packaging==16.8,py==1.4.33,pycparser==2.17,pyOpenSSL==16.2.0,pyparsing==2.2.0,pytest==3.0.7,pytest-base-url==1.3.0,pytest-metadata==1.3.0,pytest-xdist==1.15.0,requests==2.13.0,six==1.10.0
py27 runtests: PYTHONHASHSEED='1188635590'
py27 runtests: commands[0] | pytest --junit-xml=results/py27.xml --log-raw=results/py27.log -k ie
============================= test session starts ==============================
platform darwin …

update ie6 tests to reflect new build, xfail where appropriate

---

tests/e2e/tests/test_redirects.py

Closes #103 
Remove xfails now that tests are passing.
prod run -`tox -- -n 4 --base-url=http://download.mozilla.org -k ie`
* https://gist.github.com/m8ttyB/c551a94ee845c5a3d942bf05a2aac2d5
stage run -`tox -- -n 4 -k ie`
* https://gist.github.com/m8ttyB/45aac6a55f1d8c0ce0e7b2fd44d04ffb

remove ie6 xfails from e2e tests

---

tests/e2e/tests/test_smoketests.py

xfail this test until we can get routing from our Jenkins env to ship-it sorted.
closes #112

xfail test

---

tests/e2e/Jenkinsfile
tests/e2e/tox.ini

@davehunt / @m8ttyB / @oremj r?
Ad-hoc run here: https://fx-test-jenkins-dev.stage.mozaws.net:8443/job/bouncer.adhoc/18/console
For the full log: https://gist.github.com/stephendonner/1c135b945f2d380b0e9c277c26b078bd
Background blog post: http://davehunt.co.uk/2017/04/10/reporting-test-results-to-treeherder.html

Submit to Treeherder; bump shared-library version

---

tests/e2e/tests/releng_utils.py
tests/e2e/tests/test_redirects.py

Update to the winxp tests. closes #119 
Test runs using `tox -- -k winxp`:
* Prod run - https://gist.github.com/be8d3cf252ac57d2031878bfc7cee789
* State run - https://gist.github.com/4789ec270d526437b7c025f34e265bf4

update winxp tests to use product-details + update xp tests

---

tests/e2e/tests/test_redirects.py

Closes #122 
Test results when run against prod & stage:
```e2e git:(issue-122) ✗ tox -- --base-url=https://download.mozilla.org -k winxp
py27 installed: apipkg==1.4,appdirs==1.4.3,asn1crypto==0.22.0,blessings==1.6,cffi==1.10.0,cryptography==1.8.1,enum34==1.1.6,execnet==1.4.1,idna==2.5,ipaddress==1.0.18,mozlog==3.4,packaging==16.8,py==1.4.33,pycparser==2.17,pyOpenSSL==16.2.0,pyparsing==2.2.0,pytest==3.0.7,pytest-base-url==1.3.0,pytest-metadata==1.3.0,pytest-xdist==1.15.0,requests==2.13.0,six==1.10.0
py27 runtests: PYTHONHASHSEED='3937497833'
py27 runtests: commands[0] | pytest --junit-xml=results/py27.xml --log-raw=results/py27_raw.txt --log-tbpl=results/py27_tbpl.txt --base-url=https://download.mozilla.org -k winxp
================================================================ test …
```

remove firefox-esr-sha1 winxp checks

---

.pyup.yml

In an effort to reduce the frequency with which pyup creates prs I've reduced it's scope to only submit prs for security related updates.
closes #138

Add pyup config - update security related pkgs only

---

tests/e2e/tests/releng_utils.py

Update tests to pull the correct ESR build information from https://product-details.mozilla.org/1.0/firefox_versions.json.
Eventually the need to select from one of the two esr products([`FIREFOX_ESR_NEXT` and `FIREFOX_ESR`) will go away .. iirc Firefox 59.

Update esr tests to use current esr release info

---

tests/e2e/tests/releng_utils.py

Preparing this patch in case the result of investigation into [bug 1378082](https://bugzilla.mozilla.org/show_bug.cgi?id=1378082) is that we no longer want to be checking the firefox-latest-aurora alias.

Bug 1378082: Remove checks for firefox-latest-aurora alias

---

tests/e2e/Jenkinsfile

Passing ad-hoc here: https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/bouncer.adhoc/11/console

Bump shared-library version to 1.9

---

tests/e2e/tests/test_base.py
tests/e2e/tests/test_redirects.py
tests/e2e/tests/test_smoketests.py

This is so that pytest rewrites the assertions for improved failure messages.
Before:
```
assert fx_pkg_name in response.url, \
'Failed: Expected product str did not match what was returned %s' % \
>           self.response_info_failure_message(base_url, get_params, response)
E       AssertionError: Failed: Expected product str did not match what was returned Failed on http://bouncer-bouncer.stage.mozaws.net Using {'product': 'firefox-beta-latest', 'lang': 'en-US', 'os': 'win'}. Response URL: http://download.cdn.mozilla.net/pub/firefox/releases/58.0b8/win32/en-US/Firefox%20Setup%2058.0b8.exe Content-Type: application/x-msdos-programResponse Headers: Content-Length: 36371520Response Headers: x-amz-replication-status: COMPLETEDResponse Headers: Last-Modified: Thu, 30 Nov 2017 23:12:14 …
```

Renamed base.py to test_base.py

---

tests/e2e/tests/releng_utils.py
tests/e2e/tests/test_redirects.py

We've had failures for `test_verify_locales_redirect_to_the_expected_product` for the last 16 hours (since 17-Jan-2018 18:30:00) due to version 59.0b1 appearing in https://product-details.mozilla.org/1.0/firefox_primary_builds.json. Speaking to @pmac and @oremj in #stubby we should be safe to filter these by the versions specified in https://product-details.mozilla.org/1.0/firefox_versions.json. This is what I've done in this patch, but I've also made these versions test parameters, which improves reporting and running these tests in parallel.

Limit locale versions to firefox_versions and parametrize them

---

tests/e2e/setup.cfg
tests/e2e/tests/test_base.py

We had a couple of tests fail recently but there was a lack of details provided in the trace. This patch will show local variables (safe because we're not using any confidential values in this suite) on failure, and avoids an UnboundLocalError where we reference a variable that could not be assigned.

Improve information provided in the event of a test failure

---

tests/e2e/tests/test_base.py

We've seen a couple of failures when the response is not a 200 and no redirect occurs. This allows the assertion to fail rather than raising because the history is empty.

Use response URL when history is empty (no redirect occurs)

---

tests/e2e/Jenkinsfile

@oremj @m8ttyB r?
I intentionally didn't add a cron trigger, because go-bouncer.prod and go-bouncer.stage are set to run at different intervals on https://qa-master.fxtest.jenkins.stage.mozaws.net/
This change, at least, makes sense for both jobs.
Passing ad-hoc here: https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/go-bouncer.adhoc/120/console

Poll for SCM changes every 5 minutes

---

.pyup.yml

Passing ad-hoc job here: https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/go-bouncer.adhoc/139/console
Not sure the original ```flake8``` path worked, due to missing the missing ```:```, but that's unused now anyhow.
@oremj @m8ttyB @davehunt r?

Fix path to combined requirements.txt, for pyup

---

tests/e2e/Dockerfile

@davehunt @oremj @m8ttyB r?
Passing ad-hoc here: https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/go-bouncer.adhoc/153/console
If we don't skip the lockfile, we either end up with errors (in recent pipenv versions), or we do redundant work, since we don't use the Pipfile.lock (due to it not being updated fully by @pyup-bot yet).

Restore --skip-lock

---

tests/e2e/Dockerfile

@davehunt @oremj @m8ttyB 
This quells the red warning/nagging text[0]:
```
17:01:00 You are using pip version 9.0.1, however version 9.0.2 is available.
17:01:00 You should consider upgrading via the 'pip install --upgrade pip' command.
```
Ad-hoc build here: https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/go-bouncer.adhoc/164/consoleFull
[0] https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/go-bouncer.adhoc/163/consoleFull

Quell pip-version upgrade warning

---

.pyup.yml

My rationale for this change: not all security/stability updates are denoted as such (at least, not to PyPI, etc.).  A weekly batch, on Monday, is easier to deal with (IMHO), and should give us enough time (rest of the week) if we need/want to revert, for any reason.
@m8ttyB @davehunt @oremj r?

Get all dependency updates, each Monday

---

tests/e2e/tests/test_redirects.py

winxp (and vista) have been pinned to receive `52.9.0 esr` as part of the deprecation process. See  https://bugzilla.mozilla.org/show_bug.cgi?id=1319164 for additional information.
closes #253

pin winxp builds to 52.9.0 esr builds

---

tests/e2e/Pipfile

There's a bit too much in https://github.com/mozilla-services/go-bouncer/pull/275, so just trying to unfurl + separate PRs.
@oremj @m8ttyB r?

Update flake8-isort to latest, version 2.6.0

---

tests/e2e/Pipfile

Sorry, ignore the branch name.
With this and https://github.com/mozilla-services/go-bouncer/pull/284, we can hopefully close out https://github.com/mozilla-services/go-bouncer/pull/281.

Update pytest-html to 1.20.0

---

handlers.go
handlers_test.go

Fixes https://github.com/mozilla-services/go-bouncer/issues/367
---
The intention was to send users on old OSX to ESR78 installers; that worked while the esr-next aliases pointed at esr78, but that has not been the case for several years now, so this code stopped working with the initial esr91 release.
This reverts commit 9bf9a0de2610de4a6c1c840af7843757b5c2c282.

Revert "Send OSX 10.9/10/11 to ESR alias (#345)"

---

Dockerfile

Reverts mozilla-services/go-bouncer#382
This is causing failures on stage, similar to what was described in #374.

Revert "Switch back to regular golang 1.20 docker image"

---

fixtures/data.sql
handlers.go
handlers_test.go

Requests without a referer or with a referer other than mozilla.org will download the latest ESR 115 build unless they request a non-firefox product or a firefox MSI build.
Requests coming from mozilla.org are excluded because (1) we assume bedrock always pass the right product/os/lang, and (2) this allows users to download _any_ build from mozilla.org (e.g. from the "all versions" page).

Bug 1925978 - Let Windows 7/8/8.1 clients download ESR 115

---

docker/initdb.d/02-data.sql

FWIW, I used this node script to verify all the envs (except dev because I don't think we updated dev).
```javascript
const assert = require("node:assert");
(async () => {
const args = process.argv.slice(2);
const baseUrl = args[0] ?? "https://download.mozilla.org";
const compression = args[1] ?? "xz";
const version = args[2] ?? 135;
for (const [product, expectedPattern] of [
[
"firefox-nightly-latest",
`/firefox/nightly/latest-mozilla-central-l10n/firefox-${version}.0a1.en-US.linux-(i686|x86_64|aarch64).tar.${compression}`,
],
[
"firefox-nightly-latest-ssl",
`/firefox/nightly/latest-mozilla-central/firefox-${version}.0a1.en-US.linux-(i686|x86_64|aarch64).tar.${compression}`,
],
[
"firefox-nightly-latest-l10n",
`/firefox/nightly/latest-mozilla-central-l10n/firefox-${version}.0a1.en-US.linu …
```

Bug 1934132 - Add some Linux locations to localdev data fixtures

---

docker/initdb.d/02-data.sql
docker/nginx/default.conf
handlers.go
handlers_test.go

Bug 1928350 - Let macOS 10.12 to 10.14 clients download ESR 115
