mozilla-services/go-bouncer

- main.go
- mozlog/mozlog.go
- mozlog/mozlog_test.go
https://mana.mozilla.org/wiki/display/CLOUDSERVICES/Logging+Standard
@mostlygeek r?
> log in a format heka can read

- handlers.go
- main.go
> Add healthhandler

- fixtures/data.sql
- handlers.go
- handlers_test.go
Sends Windows XP Firefox downloads to the last SHA1 signed Firefox release.
> handlers: add detection from Windows XP agents

- handlers.go
- handlers_test.go
> Serve full installer instead of stub for XP

- handlers.go
- handlers_test.go
> Pin thunderbird sha1 builds.

- tests/e2e/tests/test_redirects.py
Update the rule set for the winxp tests
Reference work - https://bugzilla.mozilla.org/show_bug.cgi?id=1290737
> update win xp rules

- tests/e2e/README.md
> Fix base url

- tox.ini
It ain't easy being green: https://requires.io/github/mozilla-services/go-bouncer/requirements/?branch=master
@m8ttyB / @oremj r?
> Pick up latest dependency-packages versions.

- tests/e2e/tests/test_redirects.py
* fix a pep8 error
* the logic in the assertion and conditional statement
Note: stage still needs to be sync'd. Test should pass against prod.
> fix url scheme checks

- tests/e2e/tests/test_redirects.py
An additional rule set. Stage and production test runs will be fixed with this latest update to the tests
> update vista test

- README.md
- handlers.go
- handlers_test.go
- main.go
> Add -pinned-baseurl to support a SHA1 enabled bouncer

- tests/e2e/README.md
> Remove extraneous trailing slashes from base-url

- fixtures/data.sql
- handlers.go
- handlers_test.go
- scripts/create_docker_testdb
https://bugzilla.mozilla.org/show_bug.cgi?id=1308706
> Do not direct win64 requests to sha1 products.

- tests/e2e/tests/releng_utils.py
Remove an extra space that crept in and is preventing flake8 from allowing the build to pass.
> remove extra space

- tests/e2e/tests/base.py
- tests/e2e/tests/releng_utils.py
- tests/e2e/tests/test_redirects.py
> Remove a few typos

- tests/e2e/tests/test_redirects.py
> bump esr version for winxp

- tests/e2e/tests/test_smoketests.py
This improves coverage and failure reporting, so a single failing alias does not cause the coverage of the remaining aliases to be lost.
> Add alias and version parameters to test_verify_firefox_aliases_redirect_to_correct_products

- tests/e2e/Jenkinsfile
@m8ttyB / @oremj / @davehunt r?
This change is just a follow-up for this repo, based on the same (tested + merged) changes to:
https://github.com/mozilla/mozillians-tests/pull/350
https://github.com/mozilla/Addon-Tests/pull/987
https://github.com/mozilla/fxapom/pull/136
Ad-hoc job: https://fx-test-jenkins-dev.stage.mozaws.net:8443/job/bouncer.adhoc/86/console
> Switch to libraries declaration

- tests/e2e/.gitignore
- tests/e2e/requirements/flake8.txt
- tests/e2e/setup.cfg
- tests/e2e/tests/base.py
- tests/e2e/tests/test_redirects.py
- tests/e2e/tests/test_smoketests.py
I've bundled a few changes here, but kept separate commits. I'd be happy to split into multiple pull requests if preferred.
* Added flake8-isort to check sort order of imports
* Include the locale name in the test id instead of `locale0`, `locale1`, etc
* Verify HTTP requests to avoid warnings
* Add local test results to `.gitignore`
> Add flake8-sort, improve test ids, and verify requests

- tests/e2e/requirements/tests.txt
@oremj / @m8ttyB r?
Passing ad-hoc here: https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/bouncer.adhoc/25/console
> Update test requirements

- tests/e2e/Jenkinsfile
@oremj / @m8ttyB r?  And, mind holding off on merging, if r+d, until @davehunt or I can confirm we're good-to-go from the Jenkins side?  (Should be soon; thanks!)
Ad-hoc job here: https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/bouncer.adhoc/26/console
> Set number of pytest processes via env variable

- tests/e2e/tox.ini
@m8ttyB / @oremj r?
Passing ad-hoc build here: https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/bouncer.adhoc/27/console
> Pass along Git env variables to ActiveData

- tests/e2e/tests/test_redirects.py
Thanks for spotting this @m8ttyB!
> Remove debug print statement

- tests/e2e/Jenkinsfile
- tests/e2e/requirements.txt
Passing adhoc: https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/go-bouncer.adhoc/93/
> Add HTML report to Jenkins for end-to-end tests

- tests/e2e/Jenkinsfile
Per the 3rd best practice on https://github.com/jenkinsci/pipeline-examples/blob/0b834c0691b96d8dfc49229ba6effd66470bdee4/docs/BEST_PRACTICES.md#jenkinsfiles-and-multibranch
@oremj @m8ttyB @davehunt r?
> Add Groovy hashbang

- .pyup.yml
- tests/e2e/.gitignore
- tests/e2e/Dockerfile
- tests/e2e/Pipfile
- tests/e2e/requirements.txt
Built and tested locally; passing build here: https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/go-bouncer.adhoc/149/console
I think we'll need @davehunt to review this, so it can wait until he's back from PTO.
> Convert to using Pipfile

- tests/e2e/Jenkinsfile
> Only apply triggers for the master branch

- tests/e2e/Jenkinsfile
@m8ttyB @oremj @davehunt r?
Passing build here: https://qa-preprod-master.fxtest.jenkins.stage.mozaws.net/job/go-bouncer/view/change-requests/job/PR-250/2/console
> Bug 1476402: Audit & fix SCM polling for Multi-branch Pipeline support

- tests/e2e/Pipfile
> Bump pytest-xdist to latest, version 1.25.0

- tests/e2e/Pipfile
> Bump mozlog to latest, version 3.10

- tests/e2e/Pipfile
> Bump flake8 to 3.7.1

- tests/e2e/Pipfile
> Bump pytest-xdist; update pypi URL

- handlers.go
- handlers_test.go
> Redirect to https://www.mozilla.org/

- handlers.go
- handlers_test.go
> Allow osx to be attributable

- .circleci/config.yml
- .gitignore
> Add codecov integration

- handlers.go
I noticed a comment is no longer valid so I removed it, and the other change is formatting.
> Fix comments in handlers.go

- bouncer/db.go
- bouncer/db_test.go
- docker/initdb.d/01-schema.sql
- docker/initdb.d/02-data.sql
See https://bugzilla.mozilla.org/show_bug.cgi?id=1929196 for more details.
> Bug 1929196 - Remove unused db code

- bouncer/db.go
- bouncer/db_test.go
- handlers_test.go
It isn't 100% but that's getting close, especially with the other PRs that are getting rid of code we don't need or want.
> Bug 1929984 - Add missing test coverage

- .dockerignore
https://hackerone.com/reports/3034793
https://mozilla-hub.atlassian.net/browse/SVCSE-2611
> fix: adding gha-creds-*.json to ignore
